# ===================================================================
# Spring Boot configuration for the "heroku" profile.
#
# This configuration overrides the application.yml file.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

eureka:
    instance:
        hostname: bb-skygreen-2001.herokuapp.com
        non-secure-port: 80
        prefer-ip-address: false
    client:
        service-url:
            defaultZone: ${JHIPSTER_REGISTRY_URL}/eureka/

spring:
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
#        url: ${JDBC_DATABASE_URL}
#        username: ${JDBC_DATABASE_USERNAME}
#        password: ${JDBC_DATABASE_PASSWORD}

##       MySQL start
#        url: jdbc:mysql://debug.betterlife.com:3306/bb?useUnicode=true&characterEncoding=utf8&useSSL=false
#        username: root
#        password:
##       MySQL end

##       PostgreSQL start
        url: jdbc:postgresql://ec2-184-73-167-43.compute-1.amazonaws.com:5432/d7j6rsbv94esgh?sslmode=require
        username: qnhrvxklonvujs
        password: abd10c03fee5cde87f5cb8cdaaf2e95f1cd06e529766e868b253534803b51a01
##       PostgreSQL end

        hikari:
            maximumPoolSize: 8

            data-source-properties:
                cachePrepStmts: true
                prepStmtCacheSize: 250
                prepStmtCacheSqlLimit: 2048
                useServerPrepStmts: true

    jpa:
##       MySQL start
#        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#        database: MYSQL
##       MySQL end

##       PostgreSQL start
        database-platform: io.github.jhipster.domain.util.FixedPostgreSQL82Dialect
        database: POSTGRESQL
##       PostgreSQL end

        show-sql: true
        properties:
            hibernate.id.new_generator_mappings: true
            hibernate.cache.use_second_level_cache: true
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: true
            hibernate.cache.region.factory_class: io.github.jhipster.config.jcache.NoDefaultJCacheRegionFactory
    data:
        elasticsearch:
            cluster-name:
            cluster-nodes:
            properties:
                path:
                    logs: target/elasticsearch/log
                    data: target/elasticsearch/data
    mail:
        host: localhost
        port: 25
        username:
        password:
    messages:
        cache-seconds: 1
    thymeleaf:
        cache: false

liquibase:
    contexts: prod
